name: Love & Hope
email: jgbneatdesign@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Love & Hope Organization was founded in 2003 by two women, Josie Antoine, President and Lovely Paulemon, Vice President. Our mission is "to provide a loving, nurturing home and quality education for orphaned and needy children." Our vision is "to see children's lives change for the better." These values still hold true today and guide the strategic plan for Love & Hope Organization.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: forumtelecomhaiti
# github_username:  "jgbneatdesign"

# Build settings
markdown: kramdown
# theme: ""
# gems:
#   - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - assets/source
  - node_modules